openapi: 3.0.3
info:
  title: API Documentation Nhóm 2
  description: Chi tiết về API để implment cho dự án
  version: 1.0.0
servers:
  -  url: https://drpteam.vercel.app
  -  url: https://api-kyotrankmas-projects.vercel.app
tags:
  - name: users
    description: Các api liên quan tới user
paths:
  /v1/api/login: 
    post:
      tags:
        - users
      summary: Đăng nhập
      description: Đăng nhập vào hệ thống
      operationId: login
      requestBody:
        description: Thông tin đăng nhập
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/loginBody'
        required: true
      responses:
        '200':
          description: Đăng nhập thành công
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/loginSucces'      
        '404':
          description: Tài khoản không chính xác
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Vui lòng kiểm tra lại tài khoản
  /v1/api/logout:
    post:
      tags:
        - users
      summary: Đăng xuất
      description: 'Đăng xuất khỏi server'
      operationId: logoutUser
      responses:
        '200':
          description: "Đăng xuất tài khoản"
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
                    example: Đăng xuất tài khoản thành công
  /v1/api/sign-up:
    post:
      tags:
        - users
      summary: Đăng ký
      description: Đăng ký tài khoản
      operationId: signup
      requestBody:
        description: Thông tin đăng ký
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/signup'
        required: true
      responses:
        '201':
          description: Đăng ký thành công
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
                    example: Đăng ký thành công
        '400':
          description: Đăng ký thất bại
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Tên tài khoản đã tồn tại
  /v1/api/authenticate:
    post:
      tags:
        - users
      summary: Authen token cho user
      description: 'Xác thực access token cho mỗi phiên đăng nhập mà không cần đăng nhập bằng tài khoản, mật khẩu. Lưu ý: Cần truyền vào header Authorization với giá trị là Bearer + accessToken'
      operationId: authenToken
      security:
        - bearerAuth: []
      responses:
        '200':
          description: "Xác thực thành công"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authenToken'
                  
        '400':
          description: "Accesstoken không chính xác hoặc hết hạn"
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
                    example: Token not valid
        '401':
          description: "Accesstoken rỗng"
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorize user"
  /v1/api/refreshToken:
    post:
      tags:
        - users
      summary: Refresh token cho user
      description: 'Refresh token cho user khi hết hạn accessToken và tạo ra accessToken mới để duy trì đăng nhập cho user. Lưu ý: Cần truyền vào header Authorization với giá trị là Bearer + refreshToken'
      operationId: refreshToken
      security:
        - bearerAuth: []
      responses:
        '200':
          description: "Refresh token thành công"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/refreshToken'
                  
        '403':
          description: "Refresh token thất bại"
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid token
components:
  schemas:
    loginBody:
      type: object
      properties:
        username:
          type: string
          example: kyo
        password:
          type: string
          example: dieudeptrai
    loginSucces:
      type: object
      properties:
        message:      
          type: string
          example: Đăng nhập thành công
        account:
          type: object
          properties:
            id: 
              type: string
              example: 663b48fc09800f0e9bb8e758
            username: 
              type: string
              example: Kyo
            email:
              type: string
              example: quangdieu10092@gmail.com
        tokens:
          properties:
            accessToken: 
              type: string
              example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imt5byIsImlhdCI6MTYyNzQwNjYwMCwiZXhwIjoxNjI3NDA2NjAwfQ.7
            refreshToken:
              type: string
              example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imt5byIsImlhdCI6MTYyNzQwNjYwMH0.7
        apiKeyAIService:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
    signup:
      type: "object"
      properties:
        username:
          type: "string"
          example: "Kyo"
        email:
          type: "string"
          example: "Kyo@example.com"
        password:
          type: "string"
          example: "Dieudeptrai"
    refreshToken: 
      type: object
      properties:
        message:
          type: string
          example: Refresh token thành công
        accessToken:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imt5byIsImlhdCI6MTYyNzQwNjYwMCwiZXhwIjoxNjI3NDA2NjAwfQ.7
    authenToken: 
        type: object
        properties:
          status:
            type: string
            example: OK
  securitySchemes:
    bearerAuth:          
      type: http
      scheme: bearer
      bearerFormat: JWT    