@url_dev = http://localhost:3000/v1/api
### /
GET {{url_dev}}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2I0OGZjMDk4MDBmMGU5YmI4ZTc1OCIsIm5hbWUiOiJLeW8xIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzE1MTYzNzgzLCJleHAiOjE3MTUyNTAxODN9.raaJrA3kJIdDvujsyxtQ2JF6ZHj3yWuoaOgY-W0nbU4

### /admin
GET {{url_dev}}/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2I0OGZjMDk4MDBmMGU5YmI4ZTc1OCIsIm5hbWUiOiJLeW8xIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzE1MTYzMDg2LCJleHAiOjE3MTUyNDk0ODZ9.oTeJMG0SnpKvnq2m_WMLiMa8E7r6wqATVAAfHkcQZ6c
### signup
POST {{url_dev}}/sign-up
Content-Type: application/json

{
    "username": "tao",
    "email": "tao@example.com",
    "password": "tao"
}
### login
POST {{url_dev}}/login
Content-Type: application/json

{
    "username": "tao",
    "password": "tao"
}
### logout
POST {{url_dev}}/logout
Content-Type: application/json

{
}
### authenticate token
GET {{url_dev}}/authenticate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NDQ5MzI4NzU5MDIwZDUyMTdmZjg2MiIsInVzZXJuYW1lIjoidGFvIiwiZW1haWwiOiJ0YW9AZXhhbXBsZS5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTcxNTgzMzg5NSwiZXhwIjoxNzE1ODMzOTU1fQ.qsBZR-vNkrQZLg1ssrPF28fQ7-A04mxu20pHNfvozTE


### refresh token
GET {{url_dev}}/refreshtoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NDQ5MzI4NzU5MDIwZDUyMTdmZjg2MiIsInVzZXJuYW1lIjoidGFvIiwicm9sZSI6InVzZXIiLCJlbWFpbCI6InRhb0BleGFtcGxlLmNvbSIsImlhdCI6MTcxNTgzMzYzMH0.rJrZOM-hk0AOWizpT2_ZrlDKVFiPvE6NNsgtcMrvwjo