@url_dev = http://localhost:3000/v1/api
### /
GET {{url_dev}}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2I0OGZjMDk4MDBmMGU5YmI4ZTc1OCIsIm5hbWUiOiJLeW8xIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzE1MTYzNzgzLCJleHAiOjE3MTUyNTAxODN9.raaJrA3kJIdDvujsyxtQ2JF6ZHj3yWuoaOgY-W0nbU4

### /admin
GET {{url_dev}}/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NDYzNjM4NzAyN2IyYzU1YWMyMGM2NSIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcxNTg3NzUyMCwiZXhwIjoxNzE1ODc3NTgwfQ.nJmfVan9y_ENfZh5ejUMlBzP6wbYgcFEq74drMZABVQ
### signup
POST {{url_dev}}/sign-up
Content-Type: application/json

{
    "username": "csxsqwqwqwqwqqw",
    "email": "csxsqwqwqwqwqqw@gmail.com",
    "password": "admin"
}
### login
POST {{url_dev}}/login
Content-Type: application/json

{
    "username": "csxsqwqwqwqwqqw",
    "password": "123456"
}
### logout
POST {{url_dev}}/logout
Content-Type: application/json

{
}
### authenticate token
GET {{url_dev}}/authenticate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NDc3YmM3MDI5ZDA2NTE4YWEzYzIwZCIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoidXNlciIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNzE1OTYxMjcwLCJleHAiOjE3MTU5NjEzMzB9.gGqY2byVI32v6fZgYYTEDfv-Z7MZ2wR6vX7Ya0fqK2k


### refresh token
GET {{url_dev}}/refreshtoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NGIyODliN2NlZDIyODJmY2YwMmMzYSIsInVzZXJuYW1lIjoiY3N4c3F3cXdxd3F3cXF3Iiwicm9sZSI6InVzZXIiLCJlbWFpbCI6ImNzeHNxd3F3cXdxd3Fxd0BnbWFpbC5jb20iLCJpYXQiOjE3MTY4MDc2NTN9.aeQkOswAVPq6-IKkmvlEhmMFjHXLRtbantFAyhpXOIM