@url_dev = http://localhost:3000/v1/api
### /

POST {{url_dev}}/conversation/init
Content-Type: application/json

{
    "id": "664b289b7ced2282fcf02c3a"
}

### /new Chat
POST {{url_dev}}/conversation/newChat
Content-Type: application/json

{
    "id": "664775cf8786f00751600651",
    "conversation_id": "664fa77918c821bc51c1a83a",
    "query": "Hãy cho tôi hình ảnh và công thức của món gà rón"
}

### /get History
POST {{url_dev}}/conversation/getHistory
Content-Type: application/json

{
    "conversation_id": "664fa77918c821bc51c1a83a"
}

