@url_dev = http://localhost:3000/v1/api
### /

POST {{url_dev}}/conversation/init
Content-Type: application/json

{
    "id": "âs"
}

### /get Conversations by User
POST {{url_dev}}/conversation/getConversations
Content-Type: application/json

{
    "id": "664775cf8786f00751600651" 
}

### /new Chat
POST {{url_dev}}/conversation/newChat
Content-Type: application/json

{
    "conversation_id": "",
    "query": "Hãy công thức của món gà rón"
}



### /get History
POST {{url_dev}}/conversation/getHistory
Content-Type: application/json

{
    "conversation_id": "663a75104f2a0ecad05f07bc"
}

