@url_dev = http://localhost:3000/v1/api
### /

POST {{url_dev}}/conversation/init
Content-Type: application/json

{
    "id": "664b289b7ced2282fcf02c3a"
}

### /get Conversations by User
POST {{url_dev}}/conversation/getConversations
Content-Type: application/json

{
    "id": "664775cf8786f00751600651" 
}

### /new Chat
POST {{url_dev}}/conversation/newChat
Content-Type: application/json

{
    "conversation_id": "66536e2abf56f23bce0cbb7f",
    "query": "Chào cho tôi công thức làm bánh mì"
}



### /get History
POST {{url_dev}}/conversation/getHistory
Content-Type: application/json

{
    "conversation_id": "663a75104f2a0ecad05f07bc"
}

