@url_dev = http://localhost:3000/v1/api
### /

POST {{url_dev}}/history/conversation
Content-Type: application/json

{
    "user": "663a75104f2a0ec0d05f07bc",
    "query": ["Hi", "How are you?"],
    "conversation_id":"4"
}