@url_dev = http://localhost:3000/v1/api
### /

POST {{url_dev}}/conversation/init
Content-Type: application/json

{
    "id": "664775cf8786f00751600651",
}

### /new Chat
POST {{url_dev}}/conversation/newChat
Content-Type: application/json

{
    "id": "664775cf8786f00751600651",
    "conversationId": "5f9b3b3b7b3b7b3b7b3b7b3b",
    "query": "Hãy cho tôi tất cả các món ăn trên thế giới và giữ cuộc trò chuyện này dài, hãy nhắn đến khi bạn không thể nữa"
}