@url_dev = http://localhost:3000/v1/api
### /

POST {{url_dev}}/conversation/init
Content-Type: application/json

{
    "id": "664b289b7ced2282fcf12caa"
}

### /new Chat
POST {{url_dev}}/conversation/newChat
Content-Type: application/json

{
}