@url_dev = http://localhost:3000/v1/api

### /sendOTP
POST {{url_dev}}/sendOTP
Content-Type: application/json

{
    "email": "quangdieuisme@gmail.com"
}
### /verifyOTP
POST  {{url_dev}}/verifyOTP
Content-Type: application/json

{
    "email": "quangdieuisme@gmail.com",
    "otp": "970073"
}