@url_dev = http://localhost:3000/v1/api

### /sendOTP
POST {{url_dev}}/reset/getOTP
Content-Type: application/json

{
    "email": "csxsqwqwqwwwqwqqw@gmail.com"
}
### /reset Password
POST  {{url_dev}}/reset/password
Content-Type: application/json

{
    "email": "csxsqwqwqwqwqqw@gmail.com",
    "otp": "306320",
    "password": "123456"
}
