@url_dev = http://localhost:3000/v1/api
### /

POST {{url_dev}}/update/account
Content-Type: application/json

{
    "username": "Kyo1",
    "name": "Admin Dieu",
    "age": 20,
    "height": 170,
    "dateOfBirth": "1992-01-01",
    "weight": 70,
    "bmi": 24.2

}