@url_dev = http://localhost:3000/v1/api
### /

POST {{url_dev}}/update/account
Content-Type: application/json

{
    "username": "tao",
    "name": "Tao là Bố",
    "age": 38,
    "height": 171.5,
    "dateOfBirth": "2004-12-01",
    "weight": 70

}